#!/usr/bin/env python3
"""Embed the OFL-licensed PT Sans TrueType file in the native game.

Android's NativeActivity and the desktop tests use the same renderer, so the
font is linked once into each native library rather than fetched at runtime.
The source font and its SIL OFL license live in assets/fonts/.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/fonts/PT_Sans-Web-Regular.ttf"
TARGET = ROOT / "src/font_data.h"


def main():
    data = SOURCE.read_bytes()
    if data[:4] != b"\x00\x01\x00\x00":
        raise ValueError(f"Not a TrueType font: {SOURCE}")
    lines = [
        "/* Generated by tools/pack_font.py from PT Sans Regular (OFL 1.1). */",
        "/* Source and license: assets/fonts/PT_Sans-Web-Regular.ttf, OFL.txt */",
        "#ifndef PVG3_FONT_DATA_H",
        "#define PVG3_FONT_DATA_H",
        f"#define PT_SANS_TTF_SIZE {len(data)}",
        "static const unsigned char PT_SANS_TTF[PT_SANS_TTF_SIZE] = {",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.extend(["};", "#endif /* PVG3_FONT_DATA_H */", ""])
    TARGET.write_text("\n".join(lines), encoding="ascii")
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(data)} TTF bytes)")


if __name__ == "__main__":
    main()
