#!/usr/bin/env python3
"""Turn the project's RGBA PNG drawings into portable RLE sprites.

The game is a single native C library, with no Android asset loader or PNG
library. This build-time script needs only the Python standard library. Its
output is checked in so the existing desktop and Android builds both work
without an extra build step. Re-run it after changing any of the PNGs.
"""
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parents[1]
# Descriptive, stable names for the author's drawings and the game's currency
# token. The cone and bucket ducks are complete illustrations, not overlays.
# The renderer scales these original transparent PNGs when needed.
IMAGES = [
    ("KHLEBUSHEK", "assets/art/khlebushek.png"),
    ("MASK", "assets/art/dima-mask.png"),
    ("KIRILL", "assets/art/kirill.png"),
    ("DUCK", "assets/art/zombie-duck.png"),
    ("DUCK_CONE", "assets/art/duck-cone.png"),
    ("DUCK_BUCKET", "assets/art/duck-bucket.png"),
    ("ROBOT", "assets/art/queen-robot.png"),
    ("PEA", "assets/art/peashooter.png"),
    ("WALL", "assets/art/walnut.png"),
    ("SUNFLOWER", "assets/art/coin-sunflower.png"),
    ("JUMPER", "assets/art/jumper-fighter.png"),
    ("LILY", "assets/art/lily-pad.png"),
    ("MAP", "assets/art/lawn-map.png"),
    ("WATER_MAP", "assets/art/water-map.png"),
    ("MOWER", "assets/art/lawnmower.png"),
    ("COIN", "assets/art/coin-token.png"),
    ("LEVEL_BLOCK", "assets/art/Блок.png"),
    ("LEVEL_PLATFORM", "assets/art/Платформа.png"),
    ("LEVEL_TRIGGER", "assets/art/Триггер-движения.png"),
    ("LEVEL_TRIGGER_ROTATE", "assets/art/Триггер-вращения.png"),
    ("LEVEL_TRIGGER_FOREVER", "assets/art/Триггер-вечно.png"),
    ("LEVEL_TRIGGER_INVISIBILITY", "assets/art/Триггер-невидимости.png"),
    ("LEVEL_TRIGGER_NO_COLLISION", "assets/art/Триггер-нет столкновения.png"),
    ("LEVEL_FLAG", "assets/art/Флажок - финиш.png"),
    ("LEVEL_SPIKE", "assets/art/Шип.png"),
]


def png_pixels(path):
    data = path.read_bytes()
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        raise ValueError(f"Not a PNG: {path}")
    pos, compressed, width, height = 8, bytearray(), 0, 0
    while pos < len(data):
        length = int.from_bytes(data[pos:pos + 4], "big")
        kind = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + length]
        crc = int.from_bytes(data[pos + 8 + length:pos + 12 + length], "big")
        if len(chunk) != length or zlib.crc32(kind + chunk) != crc:
            raise ValueError(f"Bad PNG chunk in {path}")
        pos += 12 + length
        if kind == b"IHDR":
            width, height, depth, color, comp, filt, interlace = struct.unpack(">IIBBBBB", chunk)
            if (depth, color, comp, filt, interlace) != (8, 6, 0, 0, 0):
                raise ValueError(f"Expected non-interlaced RGBA8 PNG: {path}")
        elif kind == b"IDAT":
            compressed.extend(chunk)
        elif kind == b"IEND":
            break
    raw = zlib.decompress(compressed)
    stride = 4 * width
    if len(raw) != height * (stride + 1):
        raise ValueError(f"Bad PNG dimensions in {path}")
    previous = bytearray(stride)
    pixels = []
    offset = 0
    for _ in range(height):
        filter_type = raw[offset]
        line = bytearray(raw[offset + 1:offset + 1 + stride])
        offset += 1 + stride
        for x in range(stride):
            a = line[x - 4] if x >= 4 else 0
            b = previous[x]
            c = previous[x - 4] if x >= 4 else 0
            if filter_type == 0:
                predictor = 0
            elif filter_type == 1:
                predictor = a
            elif filter_type == 2:
                predictor = b
            elif filter_type == 3:
                predictor = (a + b) // 2
            elif filter_type == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                predictor = a if pa <= pb and pa <= pc else b if pb <= pc else c
            else:
                raise ValueError(f"Unsupported PNG filter {filter_type}: {path}")
            line[x] = (line[x] + predictor) & 255
        for x in range(0, stride, 4):
            r, g, b, alpha = line[x:x + 4]
            # Ignore the meaningless RGB channels under fully transparent pixels.
            pixels.append((alpha << 24 | b << 16 | g << 8 | r) if alpha else 0)
        previous = line
    return width, height, pixels


def rle(pixels):
    runs = []
    for color in pixels:
        if runs and runs[-1][1] == color and runs[-1][0] < 65535:
            runs[-1] = (runs[-1][0] + 1, color)
        else:
            runs.append((1, color))
    assert sum(n for n, _ in runs) == len(pixels)
    return runs


def main():
    output = ["/* Generated by tools/pack_sprites.py from the original PNGs. */",
              "/* Format: high 32 bits = run length, low 32 bits = RGBA8. */",
              "#ifndef PVG3_SPRITES_DATA_H", "#define PVG3_SPRITES_DATA_H", "",
              "enum { " + ", ".join("SPR_" + name for name, _ in IMAGES) + ", SPR_COUNT };", ""]
    sprite_table = []
    for name, filename in IMAGES:
        width, height, pixels = png_pixels(ROOT / filename)
        runs = rle(pixels)
        output += [f"/* {filename} ({width}x{height}, {len(runs)} runs) */",
                   f"static const uint64_t packed_{name.lower()}[] = {{"]
        for i in range(0, len(runs), 5):
            output.append("    " + ", ".join(f"0x{n:08x}{color:08x}ULL" for n, color in runs[i:i + 5]) + ",")
        output += ["};", ""]
        sprite_table.append(f"    {{ {width}, {height}, packed_{name.lower()}, {len(runs)} }}")
    output += ["static const SpritePacked SPRITE_DATA[SPR_COUNT] = {",
               ",\n".join(sprite_table), "};", "", "#endif /* PVG3_SPRITES_DATA_H */", ""]
    target = ROOT / "src" / "sprites_data.h"
    target.write_text("\n".join(output), encoding="utf-8")
    print(f"Wrote {target.relative_to(ROOT)} ({target.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
