#!/bin/sh
# Writes the Firebase configuration used by the native game and by the website
# from the environment, so the database address and the optional ?auth= token
# never have to be committed.
#
#   PVG3_DATABASE_HOST=pvg3-ae824-default-rtdb.firebaseio.com \
#   PVG3_DATABASE_AUTH='' sh tools/write_online_config.sh
#
# Without PVG3_DATABASE_HOST the public default is kept. Both values are
# whitelisted character by character, so a stray quote or newline in a CI secret
# can never break the generated C header or JavaScript module.
set -eu

default_host='pvg3-ae824-default-rtdb.firebaseio.com'
host="${PVG3_DATABASE_HOST:-$default_host}"
auth="${PVG3_DATABASE_AUTH:-}"

case "$host" in
  ''|*[!A-Za-z0-9._-]*)
    echo 'PVG3_DATABASE_HOST may only contain letters, digits, dot, dash and underscore.' >&2
    exit 1;;
esac
case "$auth" in
  *[!A-Za-z0-9._~+/=-]*)
    echo 'PVG3_DATABASE_AUTH may only contain URL-safe token characters.' >&2
    exit 1;;
esac

cat > src/online_config_secret.h <<EOF
/* Generated by tools/write_online_config.sh from the environment. Do not commit. */
#define PVG3_DATABASE_HOST "$host"
#define PVG3_DATABASE_AUTH "$auth"
EOF

cat > online/firebase-secret.js <<EOF
/* Generated by tools/write_online_config.sh from the environment. Do not commit. */
export const DATABASE_HOST = "$host";
export const DATABASE_AUTH = "$auth";
EOF

echo "Firebase configuration written for $host"
