#!/bin/sh
# Writes the Firebase configuration used by the native game and by the website
# from the environment, so the database address and the optional ?auth= token
# never have to be committed.
#
#   PVG3_DATABASE_HOST=your-project-default-rtdb.firebaseio.com \
#   PVG3_DATABASE_AUTH='' sh tools/write_online_config.sh
#
# An empty PVG3_DATABASE_HOST keeps the encoded default that ships with the
# sources. Both values are whitelisted character by character, so a stray quote
# or newline in a CI secret can never break the generated C header or the
# JavaScript module.
#
#   sh tools/write_online_config.sh --encode <host> [key]
#
# prints the encoded form of <host> (hex of every byte XOR the key) together
# with the key, ready to be pasted into src/online_config.h and
# online/firebase-config.js. This is hiding the address from a plain-text read
# of the repository, not cryptography: the key sits next to the value.
set -eu

encode() {
    awk -v host="$1" -v key="$2" 'BEGIN {
        for (n = 32; n < 127; n++) ord[sprintf("%c", n)] = n;
        if (length(key) == 0) {print "empty key" > "/dev/stderr"; exit 1;}
        out = "";
        for (i = 1; i <= length(host); i++) {
            c = substr(host, i, 1); k = substr(key, ((i - 1) % length(key)) + 1, 1);
            if (!(c in ord) || !(k in ord)) {
                print "only printable ASCII can be encoded" > "/dev/stderr"; exit 1;}
            a = ord[c]; b = ord[k]; v = 0; p = 1;
            for (bit = 0; bit < 8; bit++) {
                if ((a % 2) != (b % 2)) v += p;
                a = int(a / 2); b = int(b / 2); p *= 2;
            }
            out = out sprintf("%02x", v);
        }
        printf "key: %s\nhex: %s\n", key, out;
    }'
}

if [ "${1:-}" = '--encode' ]; then
    [ $# -ge 2 ] || { echo 'Usage: write_online_config.sh --encode <host> [key]' >&2; exit 1; }
    encode "$2" "${3:-}"
    exit 0
fi

host="${PVG3_DATABASE_HOST:-}"
auth="${PVG3_DATABASE_AUTH:-}"

case "$host" in
  *[!A-Za-z0-9._-]*)
    echo 'PVG3_DATABASE_HOST may only contain letters, digits, dot, dash and underscore.' >&2
    exit 1;;
esac
case "$auth" in
  *[!A-Za-z0-9._~+/=-]*)
    echo 'PVG3_DATABASE_AUTH may only contain URL-safe token characters.' >&2
    exit 1;;
esac

native=src/online_config_secret.h
web=online/firebase-secret.js

cat > "$native" <<EOF
/* Generated by tools/write_online_config.sh from the environment. Do not commit. */
EOF
cat > "$web" <<EOF
/* Generated by tools/write_online_config.sh from the environment. Do not commit. */
EOF

[ -n "$host" ] && cat >> "$native" <<EOF
#define PVG3_DATABASE_HOST "$host"
EOF
[ -n "$host" ] && cat >> "$web" <<EOF
export const DATABASE_HOST = "$host";
EOF

cat >> "$native" <<EOF
/* Optional token appended as ?auth= to every REST request. */
#define PVG3_DATABASE_AUTH "$auth"
EOF
cat >> "$web" <<EOF
/* Optional ?auth= token appended to every request. */
export const DATABASE_AUTH = "$auth";
EOF

echo "Firebase configuration written for ${host:-the encoded default host}"
